#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Payroc_ShortenURL
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="URL Transform")]
	public partial class Linq2SQLDataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertURL(URL instance);
    partial void UpdateURL(URL instance);
    partial void DeleteURL(URL instance);
    #endregion
		
		public Linq2SQLDataContext() : 
				base(global::System.Configuration.ConfigurationManager.ConnectionStrings["URL_TransformConnectionString"].ConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2SQLDataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2SQLDataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2SQLDataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public Linq2SQLDataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<URL> URLs
		{
			get
			{
				return this.GetTable<URL>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.URLS")]
	public partial class URL : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private string _LongURL;
		
		private string _ShortURL;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnLongURLChanging(string value);
    partial void OnLongURLChanged();
    partial void OnShortURLChanging(string value);
    partial void OnShortURLChanged();
    #endregion
		
		public URL()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LongURL", DbType="VarChar(400) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string LongURL
		{
			get
			{
				return this._LongURL;
			}
			set
			{
				if ((this._LongURL != value))
				{
					this.OnLongURLChanging(value);
					this.SendPropertyChanging();
					this._LongURL = value;
					this.SendPropertyChanged("LongURL");
					this.OnLongURLChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_ShortURL", DbType="VarChar(400) NOT NULL", CanBeNull=false, IsPrimaryKey=true)]
		public string ShortURL
		{
			get
			{
				return this._ShortURL;
			}
			set
			{
				if ((this._ShortURL != value))
				{
					this.OnShortURLChanging(value);
					this.SendPropertyChanging();
					this._ShortURL = value;
					this.SendPropertyChanged("ShortURL");
					this.OnShortURLChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
